routes/web.php
<?php

Route::get('/test-server-ip', function(){
    dd($_SERVER['HTTP_HOST']);
});

Auth::routes(['verify' => true]);
Route::get('/user/verify/{token}', 'Auth\RegisterController@verify');

Route::get('/intro-model-display-state', function(){

    if(Auth::check()){
        Auth::user()->profile->update([
            'introModelDisplayState' => 0
        ]);
        return 1;    
    }else{
        return 0;
    }
    
});


Route::get('/', 'WelcomeController@index')->name('welcome');
Route::get('/permission-error', 'CommonController@permissionError')->name('permission');
Route::get('/not-found', 'CommonController@permissionError')->name('notFound');
Route::get('/dashboard', 'DashboardController@index')->name('dashboard');

Route::group(['middleware' => ['auth', 'verified'], 'as' => 'dashboard.', 'prefix' => 'dashboard'], function () {

    ///////////////////////////////////////////////
    //////////////////////////////////////////////
    /////////////////////////////////////////////

    /* Start Admin Routes */
    Route::get('admin', [
        'uses' => 'AdminController@index',
        'as' => 'admin.index',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manage-users', [
        'uses' => 'AdminController@manageUsers',
        'as' => 'admin.manageUsers',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manage-roles', [
        'uses' => 'AdminController@manageRoles',
        'as' => 'admin.manageRoles',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/manage-roles', [
        'uses' => 'AdminController@manageRolesAction',
        'as' => 'admin.manageRolesAction',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);


    Route::get('admin/manage-tests', [
        'uses' => 'AdminController@manageTests',
        'as' => 'admin.manageTests',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manage-translotors', [
        'uses' => 'AdminController@manageTranslotors',
        'as' => 'admin.manageTranslotors',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/general-settings', [
        'uses' => 'AdminController@generalSettings',
        'as' => 'admin.generalSettings',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/add-user', [
        'uses' => 'AdminController@addUser',
        'as' => 'admin.addUser',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/addNewUser', [
        'uses' => 'AdminController@addNewUser',
        'as' => 'admin.addNewUser',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/deleteUser', [
        'uses' => 'AdminController@deleteUser',
        'as' => 'admin.deleteUser',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/viewUser/{id?}', [
        'uses' => 'AdminController@viewUser',
        'as' => 'admin.viewUser',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/addTest/{id?}', [
        'uses' => 'AdminController@addTest',
        'as' => 'admin.addTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/addNewTest{id?}', [
        'uses' => 'AdminController@addNewTest',
        'as' => 'admin.addNewTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/editTest/{id?}', [
        'uses' => 'AdminController@editTest',
        'as' => 'admin.editTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/updateTest/{id?}', [
        'uses' => 'AdminController@updateTest',
        'as' => 'admin.updateTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/deleteTest', [
        'uses' => 'AdminController@deleteTest',
        'as' => 'admin.deleteTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/evalTests/{id?}', [
        'uses' => 'AdminController@evalTests',
        'as' => 'admin.evalTests',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/evaluateTests', [
        'uses' => 'AdminController@evaluateTests',
        'as' => 'admin.evaluateTests',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/evaluateTest/{id?}', [
        'uses' => 'AdminController@evaluateTest',
        'as' => 'admin.evaluateTest',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/submitEval/{id?}', [
        'uses' => 'AdminController@submitEval',
        'as' => 'admin.submitEval',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/updateContract/{id?}', [
        'uses' => 'AdminController@updateContract',
        'as' => 'admin.updateContract',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/updateContractLP', [
        'uses' => 'AdminController@updateContractLP',
        'as' => 'admin.updateContractLP',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/sendStatusReport', [
        'uses' => 'AdminController@sendStatusReport',
        'as' => 'admin.sendStatusReport',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/ModalWithLpDetails', [
        'uses' => 'AdminController@ModalWithLpDetails',
        'as' => 'admin.ModalWithLpDetails',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/saveModalDetails', [
        'uses' => 'AdminController@saveModalDetails',
        'as' => 'admin.saveModalDetails',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/emailFormat', [
        'uses' => 'AdminController@emailFormat',
        'as' => 'admin.emailFormat',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/addNewClient', [
        'uses' => 'AdminController@addNewClient',
        'as' => 'admin.addNewClient',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::post('admin/addNewClientPost', [
        'uses' => 'AdminController@addNewClientPost',
        'as' => 'admin.addNewClientPost',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manageClients', [
        'uses' => 'AdminController@manageClients',
        'as' => 'admin.manageClients',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manageAssignments', [
        'uses' => 'AdminController@manageAssignments',
        'as' => 'admin.manageAssignments',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/add-new-assignment', [
        'uses' => 'AdminController@addNewAssignment',
        'as' => 'admin.addNewAssignment',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::POST('admin/add-new-assignment', [
        'uses' => 'AdminController@addNewAssignmentPost',
        'as' => 'admin.addNewAssignmentPost',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::POST('admin/addNewAssignmentPost', [
        'uses' => 'AdminController@addNewAssignmentPost',
        'as' => 'admin.addNewAssignmentPost',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/viewAssigment/{id?}', [
        'uses' => 'AdminController@viewAssigment',
        'as' => 'admin.viewAssigment',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);

    Route::get('admin/manage-roles/', [
        'uses' => 'AdminController@manageRoles',
        'as' => 'admin.manageRoles',
        'middleware' => 'roles',
        'roles' => ['Admin', 'Quality Analyst']
    ]);

    Route::post('admin/manage-roles/', [
        'uses' => 'AdminController@manageRolesAction',
        'as' => 'admin.manageRolesAction',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);


    Route::post('admin/upload-file/', [
        'uses' => 'AdminController@uploadFile',
        'as' => 'admin.uploadFile',
        'middleware' => 'roles',
        'roles' => ['Admin']
    ]);


    /* End Admin Routes */

                                                                                                                                                        ///////////////////////////////////////////////
                                                                                                                                                        //////////////////////////////////////////////
                                                                                                                                                        /////////////////////////////////////////////

    /* Start Translator Routes */
    Route::get('translator', [
        'uses' => 'TranslatorController@index',
        'as' => 'translator.index',
        'middleware' => 'roles',
        'roles' => ['Translator']
    ]);

    Route::get('translator/manage-profile/{ucode?}', [
        'uses' => 'TranslatorController@manageProfile',
        'as' => 'translator.manageProfile',
        'middleware' => 'roles',
        'roles' => ['Translator', 'Admin']
    ]);

    Route::get('translator/partials/educations/fields', [
        'uses' => 'TranslatorController@educationFields',
        'as' => 'translator.partials.educations.fields',
        'middleware' => 'roles',
        'roles' => ['Translator', 'Admin']
    ]);

    Route::post('translator/update-profile', [
        'uses' => 'TranslatorController@updateProfile',

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
 
class DashboardController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware(['auth', 'verified']);
        
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
       
        switch (Auth::user()->role) {
            case 'Admin':
                return view('dashboard/admin/index');
            break;

            case 'Translator':
                return view('dashboard/translator/index');
            break;

            case 'Quality Analyst':
                return view('dashboard/quality-analyst/index');
            break;

            case 'Proof Reader':
                return view('dashboard/proof-reader/index');
            break;

            case 'Operations':
                return view('dashboard/operations/index');                
            break;

            case 'Client':
                return view('dashboard/client/index');                           
            break;
            
            default:
                return view('dashboard/translator/index');    
            break;
        }
        
    }
}

resources/views/dashboard/admin/add-assignment.blade.php
@extends('layouts.user')

@section('content')


{{ Form::open(array('url' => route('dashboard.admin.addNewAssignmentPost'), 'files'=>'true', 'method'=>'post', 'enctype'=>'multipart/form-data', 'id' => 'new-assignment', 'name' => 'new-assignment')) }}
@csrf
<input type="hidden" name="form_type" value="fileplusdata">



<div  class="row margin">
  <div class="file-field input-field col m12">
    <div class="btn">
      <span>File</span>
      <input type="file" id="assignment_file" name="assignment_file"   class="validate">
    </div>
    <div class="file-path-wrapper">
      <input class="file-path validate" type="text">
      <span class="error"><p id="assignment_file_error"></p></span>
    </div>
  </div>

  <div class="input-field col m9">
   <i class="material-icons prefix pt-2">title</i>
   <input id="assignment_name" type="text" class="form-control" name="assignment_name" value=" " readonly>
   @error('assignment_name')
   <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="assignment_name">Assignment name</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="file_ext" type="text" class="form-control" name="file_ext" value=" " readonly>
  @error('file_ext')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="file_ext">File Ext.</label>
</div>

<div class="input-field col s5">
  <i class="material-icons prefix pt-2">title</i>

  <select class="form-control" name="client_name" id="client_name" >
    <option value=""></option>
    @foreach ($getAllClients as $key => $value) {
    <option value="{{$value->id}}">{{$value->client_name}}</option>
    @endforeach
  </select>
  <label>Client Name</label>

</div>

<div class="input-field col s4">
  <i class="material-icons prefix pt-2">title</i>
  <input id="req_name" type="text" class="form-control" name="req_name">
  @error('req_name')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label>Requester Name</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="charge_code" type="text" class="form-control" name="charge_code">
  @error('charge_code')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="charge_code">Charge Code</label>
</div>

<div class="input-field col s4">
  <i class="material-icons prefix pt-2">title</i>
  <select class="form-control" name="service_type" id="service_type">
    <option value="Translation" selected>Translation</option>
    <option value="Proof Reading">Proof Reading</option>
    <option value="VGA">VGA</option>
  </select>
  <label>Service Type</label>
</div>

<div class="input-field col s4">
  <i class="material-icons prefix pt-2">title</i>
  <select class="form-control" name="service_type" id="service_type">
    <option value="Arabic" selected>Arabic</option>
    <option value="English">English</option>
  </select>
  <label>Source Language</label>
</div>

<div class="input-field col s4">
  <i class="material-icons prefix pt-2">title</i>
  <select class="form-control" name="source_lang" id="source_lang">
    <option value="English" selected>Arabic</option>
    <option value="Arabic">Arabic</option>
  </select>
  <label>Target Language</label>
</div>

<div class="input-field col s5">
  <i class="material-icons prefix pt-2">title</i>
  <select class="form-control" name="time_zone" id="time_zone">
    <option value="UTC +05:30">Asia/Kolkata</option>
    <option value="UTC +04:00">Asia/Dubai</option>
  </select>
  <label>Target Language</label>
</div>

<div class="input-field col s7">
  <input type="date" class="datepicker" id="deadline" name="deadline">
  <label for="deadline">Deadline</label>
</div>


<div class="input-field col s12">
  <textarea id="client_instructions" name="client_instructions" class="materialize-textarea"></textarea>
  <label for="client_instructions">Client Instructions</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="word_count" type="text" class="form-control" name="word_count" readonly>
  @error('word_count')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="word_count">Word Count</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="page_count" type="text" class="form-control" name="page_count" readonly>
  @error('page_count')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="page_count">Page Count</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="word_count_adj" type="text" class="form-control" name="word_count_adj" >
  @error('word_count_adj')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="word_count_adj">Word Count Adj.</label>
</div>

<div class="input-field col s3">
  <i class="material-icons prefix pt-2">title</i>
  <input id="page_count_adj" type="text" class="form-control" name="page_count_adj" >
  @error('page_count_adj')
  <span class="invalid-feedback" role="alert">
    <strong>{{ $message }}</strong>
  </span>
  @enderror
  <label for="page_count_adj">Page Count Adj.</label>
</div>


<div class="input-field col s4">
  <input type="date" class="datepicker" id="translator_deadline" name="translator_deadline">
  <label for="translator_deadline">Translator Deadline</label>
</div>

<div class="input-field col s4">
  <input type="date" class="datepicker" id="proof_reader_deadline" name="proof_reader_deadline">
  <label for="proof_reader_deadline">Proof Reader Deadline</label>
</div>

<div class="input-field col s4">
  <input type="date" class="datepicker" id="vga_deadline" name="vga_deadline">
  <label for="vga_deadline">VGA Deadline</label>
</div>

</div>



<div class="row" >
  <div class="col m3 s12  mb-3  mt-1">
    <button id="savePaymentMethodBtn" class="waves-effect waves-dark btn btn-lg btn-primary"
    type="submit">Save</button>
  </div>
  <div class="col m9 s12  mb-2  mt-1" id="messageNewAssignment">
  </div>
</div>


</form>
@endsection
@push('js')
<script src="{{ asset('js/scripts/form-layouts.js') }}" type="text/javascript"></script>
<script>

 $(() => {
  var token = document.head.querySelector('meta[name="csrf-token"]');
  const config = {
    headers: { 
      'X-CSRF-TOKEN': token.content,
      'content-type': 'multipart/form-data'
    }
  }


  $("#assignment_file").change(function(e) {
   var assignment_name, file_ext;
   var assignment_name = e.target.files[0].name;
   file_ext = assignment_name.substr((assignment_name.lastIndexOf('.') + 1));
   assignment_name = assignment_name.substring(0, assignment_name.length - file_ext.length - 1);
   $('#assignment_name').val(assignment_name);
   $('#file_ext').val(file_ext);
   formData= new FormData();
   formData.append("image", file);


   const form = document.querySelector('#new-assignment');
   var formData = new FormData(form);
   axios.post(bURL+'dashboard/translator/update-profile', formData, config)
   .then(function (res) {
    console.log(res.data.message);
    if(res.data.message === true){
      var msg = `<div class="card-alert card  lighten-5">
      <div class="card-content green-text">
      <p>Success! Assignment saved successfully and notified to all translator</p>
      </div>
      </div>`;      
    }else{
      var msg = `<div class="card-alert card  lighten-5">
      <div class="card-content red-text">
      <p>Error! Have problem regarding save this assignment</p>
      </div>
      </div>`;
    }
    $('#messageNewAssignment').html(msg);
    $('#messageNewAssignment').empty().show().html(msg).delay(3000).fadeOut(300);
  })
   .catch(function (err) {
    console.log(err);            
  }); 
   
 });




  document.getElementById('new-assignment').addEventListener('submit', function(e){
    e.preventDefault();
    /* Form Validation Start Here... */
    if($('#bank_statement_hidden').val() == 1 && $('#cancelled_cheque_hidden').val() == 1){
      var names = ['bank_country', 'bank_name', 'bank_branch_address', 'beneficiary_name', 'beneficiary_account_number', 'ifsc_code'];
    }else if($('#bank_statement_hidden').val() == 1 && $('#cancelled_cheque_hidden').val() == 0){
      var names = ['bank_country', 'bank_name', 'bank_branch_address', 'beneficiary_name', 'beneficiary_account_number', 'ifsc_code', 'cancelled_cheque',];
    }else if($('#bank_statement_hidden').val() == 0 && $('#cancelled_cheque_hidden').val() == 1){
      var names = ['bank_country', 'bank_name', 'bank_branch_address', 'beneficiary_name', 'beneficiary_account_number', 'ifsc_code', 'bank_statement'];
    }else{
      var names = ['bank_country', 'bank_name', 'bank_branch_address', 'beneficiary_name', 'beneficiary_account_number', 'ifsc_code', 'bank_statement', 'cancelled_cheque'];
    }
    var errorCount = 0;
    names.forEach((el) => {
      var val = document.forms["new-assignment"][el].value;
      if (val == null || val == "") {
        document.getElementById(el + '_error').style = 'color:red';
        document.getElementById(el + '_error').focus();
        document.getElementById(el + '_error').textContent = 'Required!!!';
        ++errorCount;
      }else{
        document.getElementById(el + '_error').textContent = '';
      }
    });
    if (errorCount) return true;
    /* Form Validation End Here... */
    const form = document.querySelector('#new-assignment');
    var formData = new FormData(form);
    axios.post(bURL+'dashboard/translator/update-profile', formData, config)
    .then(function (res) {
      console.log(res.data.message);
      if(res.data.message === true){
        var msg = `<div class="card-alert card  lighten-5">
        <div class="card-content green-text">
        <p>Success! Assignment saved successfully and notified to all translator</p>
        </div>
        </div>`;      
      }else{
        var msg = `<div class="card-alert card  lighten-5">
        <div class="card-content red-text">
        <p>Error! Have problem regarding save this assignment</p>
        </div>
        </div>`;
      }
      $('#messageNewAssignment').html(msg);
      $('#messageNewAssignment').empty().show().html(msg).delay(3000).fadeOut(300);
    })
    .catch(function (err) {
      console.log(err);            
    });          
  });
});
</script>
@endpush

resources/views/dashboard/admin/add-client.blade.php
@extends('layouts.user')

@section('content')

<div class="col s6 m6 l12" style="float: left;">
<div class="card subscriber-list-card animate fadeRight">
   <div class="card-content pb-1">
    <h4 class="card-title mb-0">Add New Client</h4>
  </div>

  
  @error('email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror


        <form  action="{{ route('dashboard.admin.addNewUser') }}"  class="login-form" method="post">
            @csrf
      
      <div class="row margin">
        <div class="input-field col s4">
         <i class="material-icons prefix pt-2">title</i>
          <input id="Client_name" type="text" class="form-control @error('Client_name') is-invalid @enderror" name="Client_name" required>
            @error('Client_name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
          <label for="Client_name">Client name</label>
        </div>
        <div class="input-field col s4">
          <i class="material-icons prefix pt-2">title</i>
          <input id="Client_Team" type="text" class="form-control @error('Client_Team') is-invalid @enderror" name="Client_Team" required>
            @error('Client_Team')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
          <label for="Client_Team">Client Team</label>
        </div>

        <div class="input-field col s4">
          <i class="material-icons prefix pt-2">title</i>
          <input id="Client_Email" type="text" class="form-control @error('Client_Email') is-invalid @enderror" name="Client_Email" required>
            @error('Client_Email')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
          <label for="Client_Email">Client Email</label>
        </div>
      </div>

      
      <div class="row margin">

        <div class="input-field col s6">
          <i class="material-icons prefix pt-2">title</i>
          <input id="Client_Phone" type="text" class="form-control @error('Client_Phone') is-invalid @enderror" name="Client_Phone" required>
            @error('Client_Phone')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
          <label for="Client_Phone">Client Phone</label>
        </div>

        <div class="input-field col s6">
          <i class="material-icons prefix pt-2">title</i>
          <input id="Requester_Name" type="text" class="form-control @error('Requester_Name') is-invalid @enderror" name="Requester_Name" required>
            @error('Requester_Name')
                <span class="invalid-feedback" role="alert">
                    <strong>{{ $message }}</strong>
                </span>
            @enderror
          <label for="Requester_Name">Requester Name</label>
        </div>
     
      </div>

  
      <br/>  
    
      <div class="row">
        <div class="input-field col s12">
          <button type="submit" class="btn waves-effect waves-light border-round gradient-45deg-purple-deep-orange col s12">Add Client</button>
        </div>
      </div>
      
    </form>
</div>
</div>
@if(Session::has('error'))
<div class="badge pink lighten-5 pink-text text-accent-4">
  {{ Session::get('error') }}
</div>
@endif
@endsection
@push('js')

<script>


</script>
@endpush

resources/views/dashboard/admin/emailFormat.blade.php
<?php
// echo '<pre>';
// print_r($languagePairRowExist);
// print_r($translatorDetails);
// die;
?>



@extends('layouts.user')

@section('content')

@php
 $translatorUcode = Request::segment(4) ?? NULL;
@endphp


<div class="row margin">
  <div class="input-field col s12">
    <table class="subscription-table responsive-table highlight">
    <thead>
     <tr>
      <th>Language Direction</th>
      <th>Current Score</th>
      <th>Current Rating</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($languagePairRowExist as $languagePairEach)
    <tr id="myTableRow_{{ $languagePairEach->id }}">
    <td>{{ $languagePairEach->name }}</td>
    <td>{{ $languagePairEach->final_score }} / 500</td>
    <td>{{ $languagePairEach->final_rating }} / 5</td>
    </tr>
    @endforeach
  </tbody>
</table>
  </div>
</div>

resources/views/dashboard/admin/manage-assignments.blade.php
@extends('layouts.user')

@section('content')

<div class="row">
  <a href="{{ route('dashboard.admin.addNewAssignment') }}">
    <div class="col s12 m6 l4">
      <div class="card padding-4 animate fadeLeft">
      <div class="col s5 m5">
      <i class="material-icons pink-text">add</i>
      </div>
      <div class="col s7 m7 right-align">
      <i class="material-icons background-round mt-5 mb-5 gradient-45deg-purple-amber gradient-shadow white-text">perm_identity</i>
      <p class="mb-0">New Assignement</p>
      </div>
      </div>
    </div>
  </a>

  <div class="col s12 m6 l5">
    <div class="card padding-4 animate fadeLeft">
    <div class="col s5 m5">
    <h5 class="mb-0"></h5>
    </div>
    <div class="col s7 m7 right-align">
    <i class="material-icons background-round mt-5 mb-5 gradient-45deg-purple-amber gradient-shadow white-text">perm_identity</i>
    <p class="mb-0">Today's Active Assignments</p>
    </div>
    </div>
  </div>

<div class="col s12 m12 l12">
  <div class="card subscriber-list-card animate fadeRight">
   <div class="card-content pb-1">
    <h4 class="card-title mb-0">All Assignments <i class="material-icons float-right">more_vert</i></h4>
  </div>
  @if(Session::has('success'))
  <div class="badge green lighten-5 green-text text-accent-4">
    {{ Session::get('success') }}
  </div>
  @endif

  <table class="subscription-table responsive-table highlight">
    <thead>
     <tr>
      <th>Assignment Code</th>
      <th>Assignment Name</th>
      <th>Assignment Duration</th>
      <th>Client Name</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    @foreach ($getAllAssigments as $getAllAssigments_vals)
   <tr id="myTableRow_{{ $getAllAssigments_vals->id }}">
    <td>{{ $getAllAssigments_vals->acode }}</td>
    <td>{{ $getAllAssigments_vals->assignment_name }}</td>
    <td>{{ $getAllAssigments_vals->duration }}</td>
    <td>{{ $getAllAssigments_vals->client_id }}</td>
    <td class="left-align">
      <a href="{{route('dashboard.admin.viewAssigment',$getAllAssigments_vals->acode)}}"><i class="material-icons pink-text">create</i></a>
    </td>
  </tr>
  @endforeach
  
  
</tbody>
</table>
</div>
</div>
</div>
@endsection
@push('js')
<script type="text/javascript">

</script>
@endpush